/// <reference lib="webworker" />
import { precacheAndRoute, createHandlerBoundToURL, matchPrecache } from 'workbox-precaching'
import { registerRoute, NavigationRoute, setCatchHandler } from 'workbox-routing'

declare const self: ServiceWorkerGlobalScope

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST)

// SPA navigation: serve index.html for all routes
const handler = createHandlerBoundToURL('/index.html')
const navigationRoute = new NavigationRoute(handler)
registerRoute(navigationRoute)

// Offline fallback
setCatchHandler(async ({ request }) => {
  if (request.destination === 'document') {
    const cachedResponse = await matchPrecache('/index.html')
    return cachedResponse || Response.error()
  }
  return Response.error()
})
